---
title: "Test1"
---

```{r}
pacman::p_load(tmap, sf, tidyverse, 
               knitr,dplyr,mapview)
```

```{r}
pacman::p_load(tmap, sf, tidyverse, 
               knitr)
```

```{r}
busstop <- st_read(dsn = "data/geospatial", 
                 layer = "BusStop")
```

```{r}
glimpse(busstop)
```


```{r}
#library(sf)

# Assuming origin_SZ is your data frame
#sf_object <- st_as_sf(origin_SZ, coords = c("geometry"), crs = 4326)


```

```{r}
#origin_SZ_sf <- st_as_sf(origin_SZ, coords = c("geometry"))

```

```{r}
mapview_test_points = mapview(busstop, cex = 3, alpha = .5, popup = NULL)

mapview_test_points
```

```{r}
area_honeycomb_grid = st_make_grid(busstop, c(250, 250), what = "polygons", square = FALSE)

# To sf and add grid ID
honeycomb_grid_sf = st_sf(area_honeycomb_grid) %>%
  # add grid ID
  mutate(grid_id = 1:length(lengths(area_honeycomb_grid)))

# count number of points in each grid
# https://gis.stackexchange.com/questions/323698/counting-points-in-polygons-with-sf-package-of-r
honeycomb_grid_sf$n_colli = lengths(st_intersects(honeycomb_grid_sf, busstop))

# remove grid without value of 0 (i.e. no points in side that grid)
honeycomb_count = filter(honeycomb_grid_sf, n_colli > 0)
```

```{r}
kable(head(busstop))
```

```{r}
tmap_mode("view")

map_honeycomb = tm_shape(honeycomb_count) +
  tm_fill(
    col = "n_colli",
    palette = "Reds",
    style = "cont",
    title = "Number of Bus Stop",
    id = "grid_id",
    showNA = FALSE,
    alpha = 0.6,
    popup.vars = c(
      "Number of collisions: " = "n_colli"
    ),
    popup.format = list(
      n_colli = list(format = "f", digits = 0)
    )
  ) +
  tm_borders(col = "grey40", lwd = 0.7)

map_honeycomb
```

```{r}
odbus = st_read("data/Apstial/origin_destination_bus_202308.csv")
```

```{r}
glimpse(odbus)
```

```{r}
odbus$ORIGIN_PT_CODE <- as.factor(odbus$ORIGIN_PT_CODE)
odbus$DESTINATION_PT_CODE <- as.factor(odbus$DESTINATION_PT_CODE) 
odbus$TOTAL_TRIPS <- as.numeric(odbus$TOTAL_TRIPS)

```

```{r}
weekday6_9 <- odbus %>%
  filter(DAY_TYPE == "WEEKDAY") %>%
  filter(TIME_PER_HOUR >= 6 &
           TIME_PER_HOUR <= 9) %>%
  group_by(ORIGIN_PT_CODE) %>%
  summarise(TRIPS = sum(TOTAL_TRIPS))
```

```{r}
kable(head(weekday6_9))
```

```{r}
write_rds(weekday6_9, "data/rds/weekday6_9.rds")
```

```{r}
weekday6_9 <- read_rds("data/rds/weekday6_9.rds")
```

```{r}
busstop <- st_read(dsn = "data/geospatial",
                   layer = "BusStop") %>%
  st_transform(crs = 3414)

```

```{r}
glimpse(busstop)
```

```{r}
honeycomb_count
```

```{r}
glimpse(honeycomb_count)
```

```{r}
glimpse(weekday6_9)
```

```{r}
glimpse(busstop)
```

```{r}
  origin_SZ <- left_join(weekday6_9 , busstop,
              by = c("ORIGIN_PT_CODE" = "BUS_STOP_N")) %>%
    rename(ORIGIN_BS = ORIGIN_PT_CODE,
           ORIGIN_SZ = LOC_DESC) %>%
    group_by(ORIGIN_SZ)%>%
    mutate(TOT_TRIPS = sum(TRIPS))
```

```{r}
origin_SZ <- left_join(weekday6_9, busstop, by = c("ORIGIN_PT_CODE" = "BUS_STOP_N")) %>%
  rename(ORIGIN_BS = ORIGIN_PT_CODE, ORIGIN_SZ = LOC_DESC) %>%
  group_by(ORIGIN_SZ) %>%
  mutate(TOT_TRIPS = sum(TRIPS)) %>%
  filter(!is.na(ORIGIN_SZ) & ORIGIN_SZ != "") %>%
  distinct(ORIGIN_SZ, .keep_all = TRUE)


```

```{r}
glimpse(origin_SZ)
```
