project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Ex1/Hands-on_Ex1.html
          - text: Hands-on Exercise 2
            href: Hands-on_Ex2/Hands-on_Ex2.html
          - text: Hands-on Exercise 3
            href: Hands-on_Ex3/Hands-on_Ex3.html
          - text: Hands-on Exercise 4
            href: Hands-on_Ex4/Hands-on_Ex04.html
      - text: In-class Exercise
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.html
          - text: In-class Exercise 2
            href: In-class_Ex/In-class_Ex2/In-class_Ex02.html
          - text: In-class Exercise 2-EHSA
            href: In-class_Ex/In-class_Ex2/In-class_Ex02EHSA.html
          - text: In-class Exercise 2-GLSA
            href: In-class_Ex/In-class_Ex2/In-class_Ex02GLSA.html
          - text: In-class Exercise 3
            href: In-class_Ex/In-class_Ex3/In-class_Ex3.html
          - text: In-class Exercise 4-GDS
            href: In-class_Ex/In-class_Ex4/In-class_Ex4.html
          - text: In-class Exercise 4-SIMS
            href: In-class_Ex/In-class_Ex4/In-class_Ex4SIMS.html
             
      - text: Take-Home Exercise
        menu: 
            - text: Take-home Exercise 1
              href: Take-home-EX1/Take-Home-Ex01.html 
            - text: Take-home Exercise 2
              href: Take-home-EX2/Take-Home-Ex02.html 
            

            
      
    right:
      - href: index.html
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

